"""Renders the daily report as Markdown and a small self-contained HTML page."""

import re
from html import escape


def render_markdown(date_str, topics_result, ip_counts, ip_trend, candidates, meta):
    lines = [f"# Reddit Daily Report - {date_str}", ""]

    lines.append("## r/anime: Most Discussed Topics")
    lines.append("")
    if topics_result["shows"]:
        lines.append("| Show | Episode Threads | Total Comments | Total Score |")
        lines.append("|---|---:|---:|---:|")
        for s in topics_result["shows"]:
            lines.append(
                f"| [{s['show']}]({s['sample_url']}) | {s['thread_count']} "
                f"| {s['total_comments']} | {s['total_score']} |"
            )
    else:
        lines.append("_No episode-discussion threads found in this period._")
    lines.append("")

    if topics_result["standalone"]:
        lines.append("### Other high-discussion posts")
        lines.append("")
        for p in topics_result["standalone"][:10]:
            lines.append(f"- [{p['title']}]({p['url']}) - {p['comments']} comments, {p['score']} score")
        lines.append("")

    lines.append("## AI Anime Circle: IP Sharing Trends")
    lines.append(f"_Subreddits: {', '.join(meta['ip_subreddits'])}_")
    lines.append("")
    lines.append("### Top IPs by mentions today")
    lines.append("")
    if ip_counts:
        lines.append("| IP | Mentions |")
        lines.append("|---|---:|")
        for ip, count in ip_counts.most_common(15):
            lines.append(f"| {ip} | {count} |")
    else:
        lines.append("_No known-IP mentions matched today._")
    lines.append("")

    lines.append(f"### Fastest rising (vs {meta['trend_window_days']}-day trailing average)")
    lines.append("")
    rising = [r for r in ip_trend if r["today"] > 0][:15]
    if rising:
        lines.append("| IP | Today | Baseline Avg | Delta | % Change | Days of History |")
        lines.append("|---|---:|---:|---:|---:|---:|")
        for r in rising:
            lines.append(
                f"| {r['ip']} | {r['today']} | {r['baseline_avg']} | {r['delta']:+} "
                f"| {r['pct_change']:+}% | {r['days_of_history']} |"
            )
    else:
        lines.append("_Not enough data yet - run this daily and trends will appear "
                      "once there's history to compare against._")
    lines.append("")

    if candidates:
        lines.append("### Unlisted names worth reviewing")
        lines.append(
            "_Repeated capitalized phrases not yet in `KNOWN_IPS` - "
            "may be new/rising titles worth adding to `config.py`._"
        )
        lines.append("")
        for phrase, n in candidates.most_common(15):
            lines.append(f"- {phrase} ({n} mentions)")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated by redditdailyscraper. Posts scanned: "
                  f"{meta['topic_post_count']} from r/anime, "
                  f"{meta['ip_post_count']} from AI-anime subreddits._")

    return "\n".join(lines)


def render_html(date_str, markdown_text):
    """Very small standalone HTML wrapper - no external CSS/JS, safe to open locally."""
    body_lines = []
    in_table = False
    for line in markdown_text.split("\n"):
        if line.startswith("# "):
            body_lines.append(f"<h1>{escape(line[2:])}</h1>")
        elif line.startswith("### "):
            body_lines.append(f"<h3>{escape(line[4:])}</h3>")
        elif line.startswith("## "):
            body_lines.append(f"<h2>{escape(line[3:])}</h2>")
        elif line.startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if all(set(c) <= {"-", ":"} for c in cells):
                continue  # markdown table separator row
            tag = "th" if not in_table else "td"
            if not in_table:
                body_lines.append("<table>")
                in_table = True
            row = "".join(f"<{tag}>{_inline_md_to_html(c)}</{tag}>" for c in cells)
            body_lines.append(f"<tr>{row}</tr>")
        else:
            if in_table:
                body_lines.append("</table>")
                in_table = False
            if line.startswith("- "):
                body_lines.append(f"<p>&bull; {_inline_md_to_html(line[2:])}</p>")
            elif line.startswith("_") and line.endswith("_") and len(line) > 1:
                body_lines.append(f"<p><em>{escape(line[1:-1])}</em></p>")
            elif line.startswith("---"):
                body_lines.append("<hr>")
            elif line.strip():
                body_lines.append(f"<p>{_inline_md_to_html(line)}</p>")
    if in_table:
        body_lines.append("</table>")

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Reddit Daily Report - {escape(date_str)}</title>
<style>
body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ border: 1px solid #ccc; padding: 0.4rem 0.6rem; text-align: left; }}
th {{ background: #f2f2f2; }}
h1, h2, h3 {{ margin-top: 1.5rem; }}
</style>
</head>
<body>
{chr(10).join(body_lines)}
</body>
</html>
"""


_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def _inline_md_to_html(text):
    parts = []
    pos = 0
    for m in _LINK_RE.finditer(text):
        parts.append(escape(text[pos:m.start()]))
        parts.append(f'<a href="{escape(m.group(2))}">{escape(m.group(1))}</a>')
        pos = m.end()
    parts.append(escape(text[pos:]))
    return "".join(parts)
